### ISSUE TITLE
tutorial 1

### ISSUE THREAD

**Issue by MatthewSteen** [open223/docs.open223.info#17]
Dedicated issue for Tutorial 1 (see #7).
- G36 4.2 VAVR is probably the best candidate. https://github.com/open223/models.open223.info/blob/add/g36-4.2/models/g36-extensions-vav-reheat.ttl

## Model Loading

1. Parsing an existing model (fetch from a raw GitHub url in the models.open223.info?)
   *Describing the model and linking to relevant classes, e.g. https://explore.open223.info/brick/Variable_Air_Volume_Box_With_Reheat.html.*
2. A couple/few basic operations on the model. 
   *For example, performing a query using RDFLib *and* https://query.open223.info/.*

**Comment by MatthewSteen** [comment]
@lazlop do you want to work on this? I have time today to start it and get a PR going, which you could take over later depending on schedules.

**Comment by lazlop** [comment]
Yes, I'm happy to work on this!

**Comment by lazlop** [comment]
@MatthewSteen @gtfierro @pdelgosha22 @steveraysteveray 

Should we create issues for each piece of documentation, assign who makes a first draft, and all try to have a first draft done mid next week so we can trade and review?

**Comment by gtfierro** [comment]
Sounds good to me



--

Dr. Gabe Fierro | https://home.gtf.fyi<https://home.gtf.fyi/>

Assistant Professor of Computer Science | Colorado School of Mines

Joint Appointment | National Renewable Energy Laboratory

________________________________
From: lazlop ***@***.***>
Sent: Friday, December 15, 2023 11:23:35 AM
To: open223/docs.open223.info ***@***.***>
Cc: Gabe Fierro ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [open223/docs.open223.info] tutorial 1 (Issue #17)

CAUTION: This email originated from outside of the Colorado School of Mines organization. Do not click on links or open attachments unless you recognize the sender and know the content is safe.


@MatthewSteen<https://github.com/MatthewSteen> @gtfierro<https://github.com/gtfierro> @pdelgosha22<https://github.com/pdelgosha22> @steveraysteveray<https://github.com/steveraysteveray>

Should we create issues for each piece of documentation, assign who makes a first draft, and all try to have a first draft done mid next week so we can trade and review?

**Comment by MatthewSteen** [comment]
If you mean one file/page (e.g. `tutorial1-model-loading.md`), then yes. Each person takes ownership of...
1. Single file/page.
2. Single issue for it.
3. Pull Request.

**Comment by MatthewSteen** [comment]
G36 4.2 TTL is available now. https://github.com/open223/models.open223.info/blob/main/models/guideline36-2021-4.2.ttl

**Comment by gtfierro** [comment]
The file is hosted at https://models.open223.info/guideline36-2021-4.2.ttl

**Comment by MatthewSteen** [comment]
> The file is hosted at https://models.open223.info/guideline36-2021-4.2.ttl

I had to use https://raw.githubusercontent.com/open223/models.open223.info/main/models/guideline36-2021-4.2.ttl for RDFLib's Graph.parse method because the above caused an error. 

<details>
<summary>stdout</summary>

```

---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
File /usr/lib/python3.10/urllib/request.py:1348, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1347 try:
-> 1348     h.request(req.get_method(), req.selector, req.data, headers,
   1349               encode_chunked=req.has_header('Transfer-encoding'))
   1350 except OSError as err: # timeout error

File /usr/lib/python3.10/http/client.py:1282, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   1281 """Send a complete request to the server."""
-> 1282 self._send_request(method, url, body, headers, encode_chunked)

File /usr/lib/python3.10/http/client.py:1328, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   1327     body = _encode(body, 'body')
-> 1328 self.endheaders(body, encode_chunked=encode_chunked)

File /usr/lib/python3.10/http/client.py:1277, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   1276     raise CannotSendHeader()
-> 1277 self._send_output(message_body, encode_chunked=encode_chunked)

File /usr/lib/python3.10/http/client.py:1037, in HTTPConnection._send_output(self, message_body, encode_chunked)
   1036 del self._buffer[:]
-> 1037 self.send(msg)
   1039 if message_body is not None:
   1040 
   1041     # create a consistent interface to message_body

File /usr/lib/python3.10/http/client.py:975, in HTTPConnection.send(self, data)
    974 if self.auto_open:
--> 975     self.connect()
    976 else:

File /usr/lib/python3.10/http/client.py:1454, in HTTPSConnection.connect(self)
   1452     server_hostname = self.host
-> 1454 self.sock = self._context.wrap_socket(self.sock,
   1455                                       server_hostname=server_hostname)

File /usr/lib/python3.10/ssl.py:513, in SSLContext.wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    507 def wrap_socket(self, sock, server_side=False,
    508                 do_handshake_on_connect=True,
    509                 suppress_ragged_eofs=True,
    510                 server_hostname=None, session=None):
    511     # SSLSocket class handles server_hostname encoding before it calls
    512     # ctx._wrap_socket()
--> 513     return self.sslsocket_class._create(
    514         sock=sock,
    515         server_side=server_side,
    516         do_handshake_on_connect=do_handshake_on_connect,
    517         suppress_ragged_eofs=suppress_ragged_eofs,
    518         server_hostname=server_hostname,
    519         context=self,
    520         session=session
    521     )

File /usr/lib/python3.10/ssl.py:1071, in SSLSocket._create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1070             raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1071         self.do_handshake()
   1072 except (OSError, ValueError):

File /usr/lib/python3.10/ssl.py:1342, in SSLSocket.do_handshake(self, block)
   1341         self.settimeout(None)
-> 1342     self._sslobj.do_handshake()
   1343 finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
Cell In[2], line 5
      2 g = Graph()
      4 # Parse in an RDF file hosted on the Internet
----> 5 g.parse("https://models.open223.info/guideline36-2021-4.2.ttl", format = 'ttl')
      6 #g.parse("https://raw.githubusercontent.com/open223/models.open223.info/main/models/guideline36-2021-4.2.ttl", format="ttl")

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/graph.py:1468, in Graph.parse(self, source, publicID, format, location, file, data, **args)
   1373 def parse(
   1374     self,
   1375     source: Optional[
   (...)
   1383     **args: Any,
   1384 ) -> "Graph":
   1385     """
   1386     Parse an RDF source adding the resulting triples to the Graph.
   1387 
   (...)
   1465 
   1466     """
-> 1468     source = create_input_source(
   1469         source=source,
   1470         publicID=publicID,
   1471         location=location,
   1472         file=file,
   1473         data=data,
   1474         format=format,
   1475     )
   1476     if format is None:
   1477         format = source.content_type

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/parser.py:401, in create_input_source(source, publicID, location, file, data, format)
    394         assert data is None
    395         assert source is None
    396     (
    397         absolute_location,
    398         auto_close,
    399         file,
    400         input_source,
--> 401     ) = _create_input_source_from_location(
    402         file=file,
    403         format=format,
    404         input_source=input_source,
    405         location=location,
    406     )
    408 if file is not None:
    409     if TYPE_CHECKING:

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/parser.py:463, in _create_input_source_from_location(file, format, input_source, location)
    461     file = open(filename, "rb")
    462 else:
--> 463     input_source = URLInputSource(absolute_location, format)
    465 auto_close = True
    466 # publicID = publicID or absolute_location  # Further to fix
    467 # for issue 130

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/parser.py:270, in URLInputSource.__init__(self, system_id, format)
    266     myheaders["Accept"] = ", ".join(acc)
    268 req = Request(system_id, None, myheaders)  # type: ignore[arg-type]
--> 270 response: addinfourl = _urlopen(req)
    271 self.url = response.geturl()  # in case redirections took place
    272 self.links = self.get_links(response)

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/_networking.py:106, in _urlopen(request)
     95 """
     96 This is a shim for `urlopen` that handles HTTP redirects with status code
     97 308 (Permanent Redirect).
   (...)
    103 :return: The response to the request.
    104 """
    105 try:
--> 106     return urlopen(request)
    107 except HTTPError as error:
    108     if error.code == 308 and sys.version_info < (3, 11):
    109         # HTTP response code 308 (Permanent Redirect) is not supported by python
    110         # versions older than 3.11. See <https://bugs.python.org/issue40321> and
    111         # <https://github.com/python/cpython/issues/84501> for more details.
    112         # This custom error handling should be removed once all supported
    113         # versions of Python handles 308.

File /usr/lib/python3.10/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File /usr/lib/python3.10/urllib/request.py:519, in OpenerDirector.open(self, fullurl, data, timeout)
    516     req = meth(req)
    518 sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 519 response = self._open(req, data)
    521 # post-process response
    522 meth_name = protocol+"_response"

File /usr/lib/python3.10/urllib/request.py:536, in OpenerDirector._open(self, req, data)
    533     return result
    535 protocol = req.type
--> 536 result = self._call_chain(self.handle_open, protocol, protocol +
    537                           '_open', req)
    538 if result:
    539     return result

File /usr/lib/python3.10/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File /usr/lib/python3.10/urllib/request.py:1391, in HTTPSHandler.https_open(self, req)
   1390 def https_open(self, req):
-> 1391     return self.do_open(http.client.HTTPSConnection, req,
   1392         context=self._context, check_hostname=self._check_hostname)

File /usr/lib/python3.10/urllib/request.py:1351, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1348         h.request(req.get_method(), req.selector, req.data, headers,
   1349                   encode_chunked=req.has_header('Transfer-encoding'))
   1350     except OSError as err: # timeout error
-> 1351         raise URLError(err)
   1352     r = h.getresponse()
   1353 except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)>

```

</details>

**Comment by gtfierro** [comment]
Weird! The certificate should be valid. Maybe that'll get fixed if we try in a couple days



--

Dr. Gabe Fierro | https://home.gtf.fyi<https://home.gtf.fyi/>

Assistant Professor of Computer Science | Colorado School of Mines

Joint Appointment | National Renewable Energy Laboratory

________________________________
From: Matt Steen ***@***.***>
Sent: Saturday, December 16, 2023 7:34:40 AM
To: open223/docs.open223.info ***@***.***>
Cc: Gabe Fierro ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [open223/docs.open223.info] tutorial 1 (Issue #17)

CAUTION: This email originated from outside of the Colorado School of Mines organization. Do not click on links or open attachments unless you recognize the sender and know the content is safe.


The file is hosted at https://models.open223.info/guideline36-2021-4.2.ttl

I had to use https://raw.githubusercontent.com/open223/models.open223.info/main/models/guideline36-2021-4.2.ttl for RDFLib's Graph.parse method because the above caused an error.

stdout


---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
File /usr/lib/python3.10/urllib/request.py:1348, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1347 try:
-> 1348     h.request(req.get_method(), req.selector, req.data, headers,
   1349               encode_chunked=req.has_header('Transfer-encoding'))
   1350 except OSError as err: # timeout error

File /usr/lib/python3.10/http/client.py:1282, in HTTPConnection.request(self, method, url, body, headers, encode_chunked)
   1281 """Send a complete request to the server."""
-> 1282 self._send_request(method, url, body, headers, encode_chunked)

File /usr/lib/python3.10/http/client.py:1328, in HTTPConnection._send_request(self, method, url, body, headers, encode_chunked)
   1327     body = _encode(body, 'body')
-> 1328 self.endheaders(body, encode_chunked=encode_chunked)

File /usr/lib/python3.10/http/client.py:1277, in HTTPConnection.endheaders(self, message_body, encode_chunked)
   1276     raise CannotSendHeader()
-> 1277 self._send_output(message_body, encode_chunked=encode_chunked)

File /usr/lib/python3.10/http/client.py:1037, in HTTPConnection._send_output(self, message_body, encode_chunked)
   1036 del self._buffer[:]
-> 1037 self.send(msg)
   1039 if message_body is not None:
   1040
   1041     # create a consistent interface to message_body

File /usr/lib/python3.10/http/client.py:975, in HTTPConnection.send(self, data)
    974 if self.auto_open:
--> 975     self.connect()
    976 else:

File /usr/lib/python3.10/http/client.py:1454, in HTTPSConnection.connect(self)
   1452     server_hostname = self.host
-> 1454 self.sock = self._context.wrap_socket(self.sock,
   1455                                       server_hostname=server_hostname)

File /usr/lib/python3.10/ssl.py:513, in SSLContext.wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    507 def wrap_socket(self, sock, server_side=False,
    508                 do_handshake_on_connect=True,
    509                 suppress_ragged_eofs=True,
    510                 server_hostname=None, session=None):
    511     # SSLSocket class handles server_hostname encoding before it calls
    512     # ctx._wrap_socket()
--> 513     return self.sslsocket_class._create(
    514         sock=sock,
    515         server_side=server_side,
    516         do_handshake_on_connect=do_handshake_on_connect,
    517         suppress_ragged_eofs=suppress_ragged_eofs,
    518         server_hostname=server_hostname,
    519         context=self,
    520         session=session
    521     )

File /usr/lib/python3.10/ssl.py:1071, in SSLSocket._create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1070             raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1071         self.do_handshake()
   1072 except (OSError, ValueError):

File /usr/lib/python3.10/ssl.py:1342, in SSLSocket.do_handshake(self, block)
   1341         self.settimeout(None)
-> 1342     self._sslobj.do_handshake()
   1343 finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
Cell In[2], line 5
      2 g = Graph()
      4 # Parse in an RDF file hosted on the Internet
----> 5 g.parse("https://models.open223.info/guideline36-2021-4.2.ttl", format = 'ttl')
      6 #g.parse("https://raw.githubusercontent.com/open223/models.open223.info/main/models/guideline36-2021-4.2.ttl", format="ttl")

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/graph.py:1468, in Graph.parse(self, source, publicID, format, location, file, data, **args)
   1373 def parse(
   1374     self,
   1375     source: Optional[
   (...)
   1383     **args: Any,
   1384 ) -> "Graph":
   1385     """
   1386     Parse an RDF source adding the resulting triples to the Graph.
   1387
   (...)
   1465
   1466     """
-> 1468     source = create_input_source(
   1469         source=source,
   1470         publicID=publicID,
   1471         location=location,
   1472         file=file,
   1473         data=data,
   1474         format=format,
   1475     )
   1476     if format is None:
   1477         format = source.content_type

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/parser.py:401, in create_input_source(source, publicID, location, file, data, format)
    394         assert data is None
    395         assert source is None
    396     (
    397         absolute_location,
    398         auto_close,
    399         file,
    400         input_source,
--> 401     ) = _create_input_source_from_location(
    402         file=file,
    403         format=format,
    404         input_source=input_source,
    405         location=location,
    406     )
    408 if file is not None:
    409     if TYPE_CHECKING:

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/parser.py:463, in _create_input_source_from_location(file, format, input_source, location)
    461     file = open(filename, "rb")
    462 else:
--> 463     input_source = URLInputSource(absolute_location, format)
    465 auto_close = True
    466 # publicID = publicID or absolute_location  # Further to fix
    467 # for issue 130

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/parser.py:270, in URLInputSource.__init__(self, system_id, format)
    266     myheaders["Accept"] = ", ".join(acc)
    268 req = Request(system_id, None, myheaders)  # type: ignore[arg-type]
--> 270 response: addinfourl = _urlopen(req)
    271 self.url = response.geturl()  # in case redirections took place
    272 self.links = self.get_links(response)

File ~/docs.open223.info/.venv/lib/python3.10/site-packages/rdflib/_networking.py:106, in _urlopen(request)
     95 """
     96 This is a shim for `urlopen` that handles HTTP redirects with status code
     97 308 (Permanent Redirect).
   (...)
    103 :return: The response to the request.
    104 """
    105 try:
--> 106     return urlopen(request)
    107 except HTTPError as error:
    108     if error.code == 308 and sys.version_info < (3, 11):
    109         # HTTP response code 308 (Permanent Redirect) is not supported by python
    110         # versions older than 3.11. See <https://bugs.python.org/issue40321> and
    111         # <https://github.com/python/cpython/issues/84501> for more details.
    112         # This custom error handling should be removed once all supported
    113         # versions of Python handles 308.

File /usr/lib/python3.10/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File /usr/lib/python3.10/urllib/request.py:519, in OpenerDirector.open(self, fullurl, data, timeout)
    516     req = meth(req)
    518 sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 519 response = self._open(req, data)
    521 # post-process response
    522 meth_name = protocol+"_response"

File /usr/lib/python3.10/urllib/request.py:536, in OpenerDirector._open(self, req, data)
    533     return result
    535 protocol = req.type
--> 536 result = self._call_chain(self.handle_open, protocol, protocol +
    537                           '_open', req)
    538 if result:
    539     return result

File /usr/lib/python3.10/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File /usr/lib/python3.10/urllib/request.py:1391, in HTTPSHandler.https_open(self, req)
   1390 def https_open(self, req):
-> 1391     return self.do_open(http.client.HTTPSConnection, req,
   1392         context=self._context, check_hostname=self._check_hostname)

File /usr/lib/python3.10/urllib/request.py:1351, in AbstractHTTPHandler.do_open(self, http_class, req, **http_conn_args)
   1348         h.request(req.get_method(), req.selector, req.data, headers,
   1349                   encode_chunked=req.has_header('Transfer-encoding'))
   1350     except OSError as err: # timeout error
-> 1351         raise URLError(err)
   1352     r = h.getresponse()
   1353 except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)>
